template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "chip1261"
__REPO__ = "lang-chp"
__UND2C__ = "chp"
__UNDEFINED__ = "Chipewyan"
__UND__ = "chp"
