template = "https://github.com/giellalt/template-lang-und"
rev_id = 252
template_sha = "00bea80a90b92870230cbd76cf7ed0fece87f2c0"

[replacements]
__GLOTTOLOG_ID__ = "chip1261"
__REPO__ = "lang-chp"
__UND2C__ = "chp"
__UNDEFINED__ = "Chipewyan"
__UND__ = "chp"
