template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "chip1261"
__REPO__ = "lang-chp"
__UND2C__ = "chp"
__UNDEFINED__ = "Chipewyan"
__UND__ = "chp"
