template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "chip1261"
__REPO__ = "lang-chp"
__UND2C__ = "chp"
__UNDEFINED__ = "Chipewyan"
__UND__ = "chp"
